seed: 42

train_data_path: "data/train/faod+caod_2001-2024_train_beijing.csv"
valid_data_path: "data/train/faod+caod_2001-2024_valid_beijing.csv"
test_data_path: "data/train/faod+caod_2001-2024_test_beijing.csv"

output_folder_path: "outputs/finetune"

scaler_path: "outputs/pretrain/input_cont_scaler.pkl"
encoder_path: "outputs/pretrain/input_cate_encoders.pkl"

dataset:
  input_cont_cols: ['MOD08_C','MOD09_C_1','MOD09_C_2','MOD09_C_3','MOD09_C_4','MOD09_C_5','MOD09_C_6','MOD09_C_7','MOD09_C_8','MOD09_C_9','MOD09_C_10',
                    'MOD09_C_11','MOD09_C_12','MOD09_C_13','MOD09_C_14','MOD09_C_15',
                    'blh_C','ps_C','t2m_C','wind_C','rh_C',
                     'bc_C','oc_C','dust_C','dust25_C','so4_C','ssa_C','ssa25_C']
  input_cate_cols: ['Month']
  task_target_cols: ['fmf','faod','caod']

dataloader:
  batch_size: 512
  num_workers: 4
  pin_memory: True
  persistent_workers: True

model:
  pretrain_ckpt_path: "outputs/pretrain/lightning_logs/version_1/checkpoints/epoch=98-step=345510.ckpt"
  n_mlp_layer: 3
  p_mlp_drop: 0.3
  lr: 0.0003

callbacks:
  model_checkpoint:
    save_top_k: 1
    monitor: "valid_r2"
    mode: "max"
  early_stopping:
    monitor: "valid_r2"
    mode: "max"
    patience: 50
    min_delta: 0.0

trainer:
  max_epochs: 150
  accelerator: "gpu"
  devices: 1
